### ISSUE TITLE
Agile process template breaks the ability to create "Plans" and "Portfolio plans"

### ISSUE THREAD

**Issue by awentzel** [microsoft/featuretimeline#209] opened 2019-08-29 20:34 UTC
**Describe the bug**
Please refer to bug at https://developercommunity.visualstudio.com/content/problem/714425/unable-to-create-a-new-plan-if-process-template-ha.html?childToView=717651#comment-717651

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[x] FireFox
[x] Safari

**Version**
[x] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**

**Comment by LiXin2014** [comment] 2019-09-03 17:52
Hi @awentzel,

Sorry that I still can't reproduce the issue you are experiencing.

I have tried to create add a new custom state "To Do" for Epic work item type in an inherited Agile process. In the project created from that process, I can add plans without any issue.

Could you provide steps to reproduce, or can we have a quick Teams meeting?

Thanks,
Xin

**Comment by LiXin2014** [comment] 2019-09-04 18:22
User has installed the extension by mistake, closing the ticket.

**Closed by LiXin2014** 2019-09-04 18:22 UTC
Labels: Portfolio Plans
