### ISSUE TITLE
Epic Roadmap is broken.

### ISSUE THREAD

**Issue by KurapatiLK** [microsoft/featuretimeline#329] opened 2021-10-29 06:16 UTC
**Describe the bug**
When an Epic was deleted which is selected in Epic Roadmap, we are getting an error "Expecting constant value. The error is caused by «)»". Epic was deleted permanently from recycle bin and Epic Roadmap was broken completely and can not be reverted back.

**Steps To Produce The Issue:**
Create some epic work items *>>* Go to Epic Roadmap *>>* Select an epic in the drop down list *>>* The roadmap is displayed *>>* Go back to the backlog and delete the epic you selected in the roadmap *>>* Go to Epic Roadmap *>>* "Expecting constant value. The error is caused by «)»"

**Result Should Be:**
The Epic Roadmap should displayed properly

**Actual Result Is:**
Expecting constant value. The error is caused by «)».

**Fix:**
Verify if last Selected Epic work item exists or not. If not, consider it blank and display the Epic Roadmap as if no epic was 
 selected before.

**Browser**
Choose a browser
[ ] IE11
[ ] Chrome
[ ] FireFox
[ ] Safari

**Version**
[ ] Azure DevOps/VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Comment by ahemwe** [comment] 2021-12-17 11:57
Same here. Any support from maintainer?

**Comment by rcalaba** [comment] 2022-01-27 09:06
Same issue here  ... any update ??

**Comment by rcalaba** [comment] 2022-01-27 09:07
BTW: Seems to be duplicate of https://github.com/microsoft/featuretimeline/issues/305 - also not yet resolved.

**Comment by danhellem** [comment] 2022-08-26 15:11
Sorry, but this code in this repo is not currently being maintained. We recommend you use the [Delivery Plans](https://docs.microsoft.com/en-us/azure/devops/boards/plans/review-team-plans?view=azure-devops) feature that is core to Azure DevOps.

**Closed by danhellem** 2022-08-26 15:11 UTC
