### ISSUE TITLE
 Feature timeline and Epic Roadmap by Microsoft DevLabs is taking longer than expected to load

### ISSUE THREAD

**Issue by ssriprashanth** [Microsoft/featuretimeline#22] opened 2018-07-27 09:24 UTC
**Describe the bug**

Getting a message as 'Feature timeline and Epic Roadmap by Microsoft DevLabs is taking longer than expected to load.'  Epic Roadmap(beta) has been added as a new option.

**Browser**
Choose a browser
[x] IE11
[x] Chrome
[ ] FireFox
[ ] Safari

**Version**
[x] VSTS
[ ] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
![image](https://user-images.githubusercontent.com/41782320/43313179-3891d86e-9187-11e8-8752-ba073d0e9033.png)

Error on chrome console
![image](https://user-images.githubusercontent.com/41782320/43314276-5db02e40-918a-11e8-8da8-3b3e29520791.png)

**Comment by ssriprashanth** [comment] 2018-07-27 09:35
This is working in TFS 2018 though and there is no Epic roadmap (beta) tab.

**Comment by cmeyer79** [comment] 2018-07-27 11:20
We are experiencing the same problem within VSTS. Unable to view the Feature Timeline as it is taking too long to Load.

**Comment by navneetg-msft** [comment] 2018-07-27 13:56
Thanks for reporting the issue, can you Clear the cache and do a hard refresh using Ctrl + F5?

**Comment by ssriprashanth** [comment] 2018-07-27 14:46
Its still not working after clearing cache and Ctrl+F5.

**Comment by cmeyer79** [comment] 2018-07-27 14:56
Mine is not working either after following the steps provided

**Comment by navneetg-msft** [comment] 2018-07-27 15:11
I am really sorry for the inconveniences, I am on my way to office, I will take a look ASAP.

**Comment by navneetg-msft** [comment] 2018-07-27 15:32
Can you open Developer tools by pressing F12 in Chrome and then do Ctrl + F5?

**Comment by ssriprashanth** [comment] 2018-07-27 15:43
Tried it. Console still gives the error

![image](https://user-images.githubusercontent.com/41782320/43330789-22cf472a-91bc-11e8-8923-43f9b5cef7d7.png)

**Comment by navneetg-msft** [comment] 2018-07-27 15:54
This really strange ... as I am not able to repro it anymore. Can you send me an email at navneetg@microsoft.com? I can setup a Skype call and diagnose with you.

**Comment by navneetg-msft** [comment] 2018-07-27 19:17
The issue seems to be with the CDN ... we are investigating.

**Comment by navneetg-msft** [comment] 2018-07-27 21:51
Thanks for reporting the issue @SEnglishSMP , the root cause is an issue with the CDN, we are trying to work with them for a resolution.

**Comment by cmeyer79** [comment] 2018-07-30 13:16
Is there any update on this issue?
Thank you

**Comment by navneetg-msft** [comment] 2018-07-30 14:00
As a workaround you can disable http/2 in Firefox browser.
* Go to about:config
* Set network.http.spdy.enabled.http2 to false
![image](https://user-images.githubusercontent.com/27786230/43401905-326bbe00-93c6-11e8-9da4-ba56b94afa86.png)

**Comment by SEnglishSMP** [comment] 2018-07-30 17:12
Using Chrome on Windows 10.  Azure region is Central US.

Chrome debugging console logs the following error:
Content?bundle=vss-bundle-basejs-vI1IxAQ10AVWwEoAF6E9t0idR3ZSaZnasnpanuPQzGJ0=:57 GET https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/workitem-feature-timeline-extension/0.0.316/1532924896769/dist/featuretimeline.js 404 ()

**Comment by navneetg-msft** [comment] 2018-07-30 17:22
The issue is fixed, please confirm that it works for you.

**Comment by navneetg-msft** [comment] 2018-07-31 06:25
Closing at this is resolved now.

**Closed by navneetg-msft** 2018-07-31 06:25 UTC

**Comment by ssriprashanth** [comment] 2018-07-31 12:00
This works fine now. Thanks.

**Comment by navneetg-msft** [comment] 2018-07-31 13:40
Thanks for confirming @ssriprashanth .

**Comment by SEnglishSMP** [comment] 2018-07-31 18:30
Fixed.  Thanks.
