### ISSUE TITLE
Extension is not displaying Epics on the left hand side of the view

### ISSUE THREAD

**Issue by jsingla** [Microsoft/featuretimeline#3] opened 2018-05-10 15:55 UTC
**Describe the bug**
On opening "Feature Timeline", although the features are displayed, the epics do not appear on the left hand side, as advertised in the readme. There are epics linked as parent to those features.

**Browser**
Choose a browser
[ ] IE11
[X] Chrome
[ ] FireFox
[X] Safari

**Version**
[ ] VSTS
[X] TFS 2017 Update 2/3
[ ] TFS 2018

**Screenshots**
Features get displayed but not Epics for those features.

Original image from extension's readme:
![main-img](https://user-images.githubusercontent.com/1568002/39879337-79dc34ba-5472-11e8-9709-f6cc4fe4873c.png)

Actual image of the issue:
![screen shot 2018-05-10 at 4 36 38 pm](https://user-images.githubusercontent.com/1568002/39879355-80ff374c-5472-11e8-9ecf-efb21206e8de.png)

**Console logs:** 
[tfs-1525966650598.log](https://github.com/Microsoft/featuretimeline/files/1992246/tfs-1525966650598.log)

**Comment by navneet-g** [comment] 2018-05-12 15:00
Thanks for reporting the issue, I was not able to reproduce the bug but checked in a defensive fix. Please upgrade to latest version and let me know if this still repros.

**Closed by navneet-g** 2018-05-12 15:00 UTC
Labels: bug
